# -*- coding: utf-8 -*-
"""MLOPS(sentimental_analysis_task).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgWUJGC31eEV6beYDl9PViaJx0mpCjad
"""

import numpy as np
import pandas as pd

data = pd.read_csv("data.csv")
data.head()

data.shape

data.info()

data.describe(include='all')

data.isnull().sum()

"""**Creating Sentiment column**"""

def create_sentiment(Rating):
  if Rating>=4:
    return 'positive'
  elif Rating<=2:
    return 'negative'
  else:
    return 'nuetral'
data['sentiment']=data['Ratings'].apply(create_sentiment)
data= data[data['sentiment'] != 'neutral']
data['sentiment'].value_counts()

"""**combining Review title and review text**"""

data['review'] = (
    data['Review Title'].fillna('') + " " +
    data['Review text'].fillna('')
)
data.head()

"""**Text Cleaning and Normalization**"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [
        lemmatizer.lemmatize(word)
        for word in words if word not in stop_words
    ]
    return " ".join(words)

data['clean_review'] = data['review'].apply(clean_text)

"""**Train-test-split**"""

from sklearn.model_selection import train_test_split

X = data['clean_review']
y = data['sentiment'].map({'negative': 0, 'positive': 1})

# Identify and remove rows where y is NaN
# This handles the 'nuetral' sentiments that were not filtered out previously.
nan_indices = y.isna()
X = X[~nan_indices]
y = y[~nan_indices]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""**Feature Extraction TF-IDF**"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

"""**Model Training**"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

"""**Model Evalution**"""

from sklearn.metrics import classification_report, f1_score

y_pred = model.predict(X_test_tfidf)

print("F1 Score:", f1_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""**Saving model**"""

import joblib

joblib.dump(model, "sentiment_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

